#!/bin/bash
ssh_cmd=$1; shift

echo "ssh_cmd: $ssh_cmd"
if [ "$ssh_cmd" == "" ]; then
	echo "ssh_cmd must be set"
	exit 1
fi


distro=$1; shift
echo "distro: $distro"
if [ "$distro" == "" ]; then
	echo "distro must be set"
	exit 1
fi


bits=$1; shift
echo "bits: $bits"
if [[ "$bits" != "32" && "$bits" != "64" ]]; then
	echo "Bits can only be 32 or 64 bit"
	exit 1
fi

case $distro in
	"arch"k)
	full_distro_name="arch-2014.09-$bits"
	;;
	"centos6")
	full_distro_name="centos6-$bits"
	;;
	"centos"|"centos7")
	full_distro_name="centos7-$bits"
	;;
	"centos-docker"|"centos7-docker")
	full_distro_name="centos7-docker-$bits"
	;;
	"debian-wheezy")
	full_distro_name="debian-wheezy-7.0-$bits"
	;;
	"debian"|"debian-jessie")
	full_distro_name="debian-jessie-8.0-$bits"
	;;
	"debian-rescue")
	full_distro_name="debian-jessie-rescue-8.0-$bits"
	;;
	"fedora22")
	full_distro_name="fedora22--$bits"
	;;
	"fedora"|"fedora23")
	full_distro_name="fedora23--$bits"
	;;
	"netbsd6")
	full_distro_name="netbsd-6.1.5-$bits"
	;;
	"netbsd"|"netbsd7")
	full_distro_name="netbsd-7.0-$bits"
	;;
	"ubuntu-precise")
	full_distro_name="ubuntu-precise-12.04-$bits"
	;;
	"ubuntu-trusty")
	full_distro_name="ubuntu-trusty-14.04-$bits"
	;;
	"ubuntu-docker"|"ubuntu-trusty-docker")
	full_distro_name="ubuntu-trusty-14.04-docker-$bits"
	;;
	"ubuntu"|"ubuntu-wily")
	full_distro_name="ubuntu-wily-15.10-$bits"
	;;
	*)
	echo "Unexpected distro $distro"
	exit 1
	;;
esac

echo "Using distro $full_distro_name"

expect_script="/tmp/$(basename $0).$$.expr"

cat > $expect_script <<EOM	
set timeout 30
spawn $ssh_cmd

set timeout 15
expect "enter selection>" {} timeout {exit 1}
send "4"
expect "enter selection>" {} timeout {exit 1}
send "2"
set timeout 90
expect "Use the ^ and v keys to select which entry is highlighted." {} timeout {exit 1}
send "v\r"
expect "Debian GNU/Linux 8 rescue hvc0" {} timeout {exit 1}
expect "rescue login:" {} timeout {exit 1}
send "root\r"
set timeout 15
expect "root@rescue:~#" {} timeout {exit 1}
send "mkfs.ext3 -L PRGMRDISK1 /dev/xvda1\r"
expect "Proceed anyway? (y,n)"
send "y\r"
expect "root@rescue:~#" {} timeout {exit 1}
send "mount -n /dev/xvda1 /mnt\r"
expect "root@rescue:~#" {} timeout {exit 1}
set timeout 60
send "tar xzf /distros/$full_distro_name.tar.gz -C /mnt\r"
expect "root@rescue:~#" {} timeout {exit 1}
set timeout 15
send "umount -n /mnt\r"
expect "root@rescue:~#" {} timeout {exit 1}
send "shutdown -r now\r"
expect "enter selection>" {} timeout {exit 1}
send 9
EOM

/usr/bin/expect $expect_script
if [ "$?" != "0" ]; then
        echo "Expect script failed."
        rm -f $expect_script
        exit 1
fi
rm -f $expect_script; exit 0

