#!/bin/bash
ssh_cmd=$1; shift

echo "ssh_cmd: $ssh_cmd"
if [ "$ssh_cmd" == "" ]; then
	echo "ssh_cmd must be set"
	exit 1
fi


distro=$1; shift
echo "distro: $distro"
if [ "$distro" == "" ]; then
	echo "distro must be set"
	exit 1
fi


bits=$1; shift
echo "bits: $bits"
if [[ "$bits" != "32" && "$bits" != "64" ]]; then
	echo "Bits can only be 32 or 64 bit"
	exit 1
fi

case $distro in
	"arch")
	full_distro_name="arch-2014.09-$bits"
	;;
	"centos6")
	full_distro_name="centos6-$bits"
	;;
	"centos"|"centos7")
	full_distro_name="centos7-$bits"
	;;
	"debian")
	full_distro_name="debian-wheezy-7.0-$bits"
	;;
	"debian-rescue")
	full_distro_name="debian-wheezy-rescue-7.0-$bits"
	;;
	"fedora")
	full_distro_name="fedora20--$bits"
	;;
	"netbsd")
	full_distro_name="netbsd-6.1.5-$bits"
	;;
	"ubuntu-precise")
	full_distro_name="ubuntu-precise-12.04-$bits"
	;;
	"ubuntu"|"ubuntu-trusty")
	full_distro_name="ubuntu-trusty-14.04-$bits"
	;;
	"ubuntu-trusty-docker")
	full_distro_name="ubuntu-trusty-14.04-docker-$bits"
	;;
	*)
	echo "Unexpected distro $distro"
	exit 1
	;;
esac

echo "Using distro $full_distro_name"

expect_script="/tmp/$(basename $0).$$.expr"

cat > $expect_script <<EOM	
set timeout 5

spawn $ssh_cmd

expect "enter selection>" { send "4" }
expect "enter selection>" { send "2" }
expect " for a command-line." { send "v\r"}
sleep 60
send "root\r"
expect "root@rescue:~#" { send "mkfs.ext3 -L PRGMRDISK1 /dev/xvda1\r"; sleep 5; send "y\r" }
expect "root@rescue:~#" { send "mount -n /dev/xvda1 /mnt\r" }
expect "root@rescue:~#" { send "tar xzf /distros/$full_distro_name.tar.gz -C /mnt\r" }
expect "root@rescue:~#" { send "umount -n /mnt\r" }
expect "root@rescue:~#" { send "shutdown -r now\r" }
expect "enter selection>" { send "9" }
EOM

/usr/bin/expect $expect_script
if [ "$?" != "0" ]; then
        echo "Expect script failed."
        rm -f $expect_script
        exit 1
fi
rm -f $expect_script; exit 0

