#!/bin/bash
#root_dir="$(test -d .git && echo "." || echo "$(git rev-parse --show-cdup)")"

ssh_cmd=$1; shift

if [ "$ssh_cmd" == "" ]; then
	echo "ssh_cmd must be set"
	exit 1
fi

hostname_long=$1; shift

if [ "$hostname_long" == "" ]; then
	echo "hostname must be set"
	exit 1
fi

hostname_short=$( echo $hostname_long | sed 's/\..*//g')

root_password=$1; shift

if [ "$root_password" == "" ]; then
	echo "Root password must be set"
	exit 1
fi


expect_script="/tmp/$(basename $0).$$.expr"

echo "Generating keys"
ansible_password=$(date +%s | shasum | base64 | head -c 64 ; echo)
ansible_public_key=$(cat $HOME/.ssh/ansible.pub)

if [ "$ansible_public_key" == "" ]; then
	echo "No ansible public key found on provisioning server"
	exit 1
fi

echo "Setting up script $expect_script"

cat > $expect_script <<EOM
set timeout 20

send_user "Test"

spawn $ssh_cmd

send_user "Shutting down server"
expect "enter selection>" {} timeout {exit 1}
send "4"
send_user "Starting server"
expect "enter selection>" {} timeout {exit 1}
send "2"
send_user "Selecting default distro"
expect "Use the ^ and v keys to select which entry is highlighted." {} timeout {exit 1}
send "\r"
expect "Use the ^ and v keys to select which entry is highlighted." {} timeout {exit 1}
send_user "Waiting for server to boot"
set timeout 300
send "\r"
send_user ""
expect "login:" {} timeout {exit 1}
set timeout 20
send "root\r"
expect "root@grlee:~#" { send "passwd\r" } timeout {exit 1}
expect ":" { send "$root_password\r" } timeout {exit 1}
expect ":" { send "$root_password\r" } timeout {exit 1}
expect "root@grlee:~#" { send "useradd -m -d /home/ansible -s /bin/bash -c \"Ansible User\" ansible;passwd ansible\r" } timeout {exit 1}
expect ":" { send "$ansible_password\r" } timeout {exit 1}
expect ":" { send "$ansible_password\r" } timeout {exit 1}
expect "root@grlee:~#" { send "adduser ansible sudo\r" } timeout {exit 1}
expect "root@grlee:~#" { send "su ansible -c 'mkdir -p /home/ansible/.ssh'\r" } timeout {exit 1}
expect "root@grlee:~#" { send "su ansible -c 'echo $ansible_public_key >> /home/ansible/.ssh/authorized_keys'\r" } timeout {exit 1}
expect "root@grlee:~#" { send "chmod 700 /home/ansible/.ssh\r" } timeout {exit 1}
expect "root@grlee:~#" { send "chmod 600 /home/ansible/.ssh/authorized_keys\r" } timeout {exit 1}
expect "root@grlee:~#" { send "echo \"ansible ALL=(ALL) NOPASSWD:ALL\" > /etc/sudoers.d/ansible\r" } timeout {exit 1}
expect "root@grlee:~#" { send "chmod 0440 /etc/sudoers.d/ansible\r" } timeout {exit 1}
expect "root@grlee:~#" { send "hostname $hostname_short\r" } timeout {exit 1}
expect "root@grlee:~#" { send "echo $hostname_short > /etc/hostname\r" } timeout {exit 1}
expect "root@grlee:~#" { send "shutdown -r now\r" } timeout {exit 1}
expect "enter selection>" { send "9\r" } timeout {exit 1}
EOM

echo "Setting up distro"
/usr/bin/expect -d $expect_script
if [ "$?" != "0" ]; then
	echo "Expect script failed."
	rm -f $expect_script
	exit 1
fi
rm -f $expect_script; exit 0
